default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: local-check
        name: local check parity
        entry: bun run check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: local-ci
        name: local ci parity
        entry: bun run ci:local
        language: system
        pass_filenames: false
        stages: [pre-push]
