//! Timing of the IPC read paths against an archive of realistic size.
//!
//! ## Responsibilities
//! - Build a synthetic archive with N visits (default 1,000,000; the product target is 14.4M)
//!   through the real schema, then let the real open path project it into the search database.
//! - Time the per-command costs that decide whether the UI waits: archive open, config load,
//!   `app_snapshot` (plaintext and encrypted), `query_history` with and without the exact total,
//!   source stats, URL detail and the wipe preview.
//! - Seed the intelligence database with derived rows (one per visit, plus stale ones) and time
//!   the doctor's stale-row checks, old query shape beside the current one.
//! - Seed search events (one per eight visits) and time Insights' frequent searches per range,
//!   plus the one-time migration that stores each event's visit time.
//! - Export the whole archive and report time, peak memory and file size per format.
//! - Report peak Rust heap and peak SQLite memory for the calls whose memory matters.
//!
//! ## Not responsible for
//! - Pass/fail thresholds. It prints numbers for `docs/architecture/ipc-performance.md`; it never
//!   runs in CI. Set `PATHKEEP_ARCHIVE_BENCH=1` to run it:
//!
//! ```sh
//! PATHKEEP_ARCHIVE_BENCH=1 PATHKEEP_ARCHIVE_BENCH_VISITS=14400000 \
//!   PATHKEEP_ARCHIVE_BENCH_DIR=/tmp/pathkeep-bench \
//!   cargo test --manifest-path src-tauri/Cargo.toml -p vault-worker \
//!   --test archive_scale_bench --release -- --nocapture
//! ```
//!
//! `PATHKEEP_ARCHIVE_BENCH_DIR` keeps the generated archive between runs (generation at 14.4M
//! takes minutes); without it a temp directory is used and removed.
//!
//! `PATHKEEP_ARCHIVE_BENCH_SECTIONS` picks sections, comma-separated: `reads`, `search`
//! (keyword search at three frequencies), `doctor`, `searches`, `export`, `encrypted`,
//! `encrypted-export`. All but `encrypted-export` run when it is unset; that one seeds a second
//! full-size archive, encrypted, and exports it, because SQLCipher decrypts every page the export
//! reads.
//! `PATHKEEP_ARCHIVE_BENCH_EXPORT_FORMATS` (default `jsonl,html`) picks the export formats; each
//! export file is deleted after it is measured.
//!
//! ## Performance notes
//! - Rows are generated by a fixed linear congruential sequence, so runs are comparable.
//! - Each timing repeats the call and reports the median and the slowest run.

use rusqlite::{Connection, params};
use std::{
    alloc::{GlobalAlloc, Layout, System},
    path::{Path, PathBuf},
    sync::atomic::{AtomicUsize, Ordering},
    time::{Duration, Instant},
};
use vault_core::{
    AppConfig, ArchiveMode, HistoryQuery, ProjectPaths,
    archive::{open_archive_connection, open_intelligence_connection},
    project_paths_with_root, save_config,
};

const PROFILES: [(&str, &str); 3] =
    [("chrome", "Default"), ("chrome", "Profile 1"), ("firefox", "default-release")];
const DOMAINS: u64 = 20_000;
const SPAN_MS: i64 = 5 * 365 * 86_400_000;
const START_MS: i64 = 1_600_000_000_000;

#[test]
fn archive_scale_bench() {
    if std::env::var("PATHKEEP_ARCHIVE_BENCH").as_deref() != Ok("1") {
        eprintln!("archive_scale_bench skipped; set PATHKEEP_ARCHIVE_BENCH=1 to run it");
        return;
    }
    let visits: u64 = std::env::var("PATHKEEP_ARCHIVE_BENCH_VISITS")
        .ok()
        .and_then(|value| value.parse().ok())
        .unwrap_or(1_000_000);
    let temp = tempfile::tempdir().expect("tempdir");
    let base = std::env::var_os("PATHKEEP_ARCHIVE_BENCH_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| temp.path().to_path_buf());

    // Browser discovery inside app_snapshot must not scan the machine's real profiles.
    let empty = base.join("no-browsers");
    std::fs::create_dir_all(&empty).expect("empty browser root");
    unsafe {
        std::env::set_var("CHB_CHROME_USER_DATA_DIR", &empty);
        std::env::set_var("CHB_FIREFOX_PROFILES_DIR", &empty);
        std::env::set_var("CHB_SAFARI_ROOT", &empty);
        std::env::set_var("CHB_TEST_KEYRING_DIR", base.join("keyring"));
    }

    println!("\n# archive_scale_bench: {visits} visits\n");
    let plain_root = base.join(format!("plain-{visits}"));
    // Seeding takes minutes and gigabytes at 14.4M, so only when a plaintext section runs.
    if ["reads", "search", "doctor", "searches", "export"].into_iter().any(wants) {
        let plain = seeded_archive(&plain_root, visits, None);
        if wants("reads") {
            bench_plaintext(&plain_root, &plain);
        }
        if wants("doctor") {
            seeded_derived_rows(&plain_root, &plain);
            bench_doctor(&plain_root, &plain);
        }
        if wants("searches") {
            bench_frequent_searches(&plain_root, &plain);
        }
        if wants("export") {
            bench_export(&plain_root, &plain, None);
        }
        if wants("search") {
            let paths = project_paths_with_root(&plain_root);
            unsafe { std::env::set_var("CHB_PROJECT_ROOT", &plain_root) };
            drop(open_archive_connection(&paths, &plain, None).expect("first open"));
            bench_search(&paths, &plain, visits);
        }
    }

    if wants("encrypted") {
        let encrypted_root = base.join("encrypted-100000");
        let encrypted = seeded_archive(&encrypted_root, 100_000, Some("bench-key"));
        bench_encrypted(&encrypted_root, &encrypted);
    }
    if named("encrypted-export") {
        let root = base.join(format!("encrypted-{visits}"));
        let encrypted = seeded_archive(&root, visits, Some("bench-key"));
        bench_export(&root, &encrypted, Some("bench-key"));
    }
}

/// True only when `PATHKEEP_ARCHIVE_BENCH_SECTIONS` names `section`: for sections too costly to
/// run by default.
fn named(section: &str) -> bool {
    std::env::var("PATHKEEP_ARCHIVE_BENCH_SECTIONS")
        .is_ok_and(|sections| sections.split(',').any(|name| name.trim() == section))
}

/// True when `PATHKEEP_ARCHIVE_BENCH_SECTIONS` is unset or names `section`.
fn wants(section: &str) -> bool {
    std::env::var("PATHKEEP_ARCHIVE_BENCH_SECTIONS")
        .map(|sections| sections.split(',').any(|name| name.trim() == section))
        .unwrap_or(true)
}

/// Compares full-rebuild and incremental batch visibility changes on the same seeded archive.
/// Run with PATHKEEP_IMPORT_BATCH_BENCH=1 and PATHKEEP_ARCHIVE_BENCH_DIR inside the checkout.
#[test]
fn import_batch_visibility_scale_bench() {
    if std::env::var("PATHKEEP_IMPORT_BATCH_BENCH").as_deref() != Ok("1") {
        return;
    }
    let visits = std::env::var("PATHKEEP_ARCHIVE_BENCH_VISITS")
        .ok()
        .and_then(|value| value.parse::<u64>().ok())
        .unwrap_or(1_000_000);
    assert!(visits >= 1_000_000);
    let temp = tempfile::tempdir_in(std::env::current_dir().expect("checkout"))
        .expect("temporary benchmark directory");
    let base = std::env::var_os("PATHKEEP_ARCHIVE_BENCH_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| temp.path().to_path_buf());
    let root = base.join(format!("plain-{visits}"));
    let mut config = seeded_archive(&root, visits, None);
    config.git_enabled = false;
    let paths = project_paths_with_root(&root);
    save_config(&paths, &config).expect("benchmark config");
    let mut archive = open_archive_connection(&paths, &config, None).expect("archive");
    let transaction = archive.transaction().expect("batch transaction");
    transaction
        .execute(
            "INSERT INTO import_batches (source_kind, source_path, profile_id, created_at,
           imported_at, status, summary_json)
         VALUES ('browser-history', '/bench', 'chrome:Default', '2026-01-01T00:00:00Z',
           '2026-01-01T00:00:00Z', 'imported', '{\"importedItems\":10000}')",
            [],
        )
        .expect("benchmark batch");
    let batch_id = transaction.last_insert_rowid();
    transaction
        .execute(
            "UPDATE visits SET import_batch_id = ?1
         WHERE id IN (SELECT id FROM visits ORDER BY id DESC LIMIT 10000)",
            [batch_id],
        )
        .expect("batch visits");
    let affected: i64 = transaction
        .query_row(
            "SELECT COUNT(DISTINCT url_id) FROM visits WHERE import_batch_id = ?1",
            [batch_id],
            |row| row.get(0),
        )
        .expect("affected URLs");
    transaction.commit().expect("batch commit");
    drop(archive);
    println!("\n## import batch visibility: {visits} visits, 10000 in batch, {affected} URLs");
    let mut revert_samples = Vec::new();
    let mut restore_samples = Vec::new();
    for _ in 0..5 {
        let started = Instant::now();
        let detail =
            vault_core::revert_import_batch(&paths, &config, None, batch_id).expect("revert batch");
        revert_samples.push(started.elapsed());
        assert_eq!(detail.batch.status, "reverted");
        assert!(!detail.note_details.iter().any(|note| note.code.contains("rebuild-needed")));
        let started = Instant::now();
        let detail = vault_core::restore_import_batch(&paths, &config, None, batch_id)
            .expect("restore batch");
        restore_samples.push(started.elapsed());
        assert_eq!(detail.batch.status, "imported");
        assert!(!detail.note_details.iter().any(|note| note.code.contains("rebuild-needed")));
    }
    for (label, mut samples) in
        [("revert_import_batch", revert_samples), ("restore_import_batch", restore_samples)]
    {
        samples.sort();
        println!(
            "| {label} | median {:.2} ms | max {:.2} ms |",
            samples[2].as_secs_f64() * 1000.0,
            samples[4].as_secs_f64() * 1000.0
        );
    }
}

fn bench_plaintext(root: &Path, config: &AppConfig) {
    let paths = project_paths_with_root(root);
    unsafe { std::env::set_var("CHB_PROJECT_ROOT", root) };

    // A reused archive from an older build migrates on this open; keep that out of the timings
    // below but report it, since it is the one-time upgrade cost.
    let started = Instant::now();
    drop(open_archive_connection(&paths, config, None).expect("first open"));
    println!(
        "first open in this process (runs pending migrations): {:.1}s\n",
        started.elapsed().as_secs_f64()
    );

    println!("## archive open (plaintext)");
    report("open_archive_connection, warm process", 20, || {
        drop(open_archive_connection(&paths, config, None).expect("open"));
    });
    let search = Connection::open(&paths.search_database_path).expect("search db");
    report("old per-open search COUNT(*) (removed)", 5, || {
        let _: i64 = search
            .query_row("SELECT COUNT(*) FROM search_documents", [], |row| row.get(0))
            .expect("count");
    });
    report("old per-open search meta upsert (removed)", 20, || {
        search
            .execute(
                "INSERT INTO search_projection_meta (key, value) VALUES ('schema_version', '4')
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [],
            )
            .expect("upsert");
    });
    report("current per-open search existence probe", 20, || {
        search.query_row("SELECT 1 FROM search_documents LIMIT 1", [], |_| Ok(())).expect("probe");
    });
    drop(search);

    println!("\n## config");
    report("load_config + App Lock hydrate + unlock check", 200, || {
        let mut config = vault_core::load_config(&paths).expect("config");
        vault_core::hydrate_app_lock_config(&paths, &mut config).expect("hydrate");
        vault_core::ensure_app_lock_unlocked(&paths, &config).expect("unlocked");
    });

    println!("\n## app_snapshot (plaintext)");
    report("app_snapshot", 10, || {
        vault_worker::app_snapshot(None).expect("snapshot");
    });

    println!("\n## query_history");
    let page = |q: Option<&str>, include_total: bool| HistoryQuery {
        q: q.map(str::to_string),
        limit: Some(100),
        include_total: Some(include_total),
        ..HistoryQuery::default()
    };
    report("browse, first page, exact total", 5, || {
        vault_core::list_history(&paths, config, None, page(None, true)).expect("query");
    });
    report("browse, first page, no total", 5, || {
        vault_core::list_history(&paths, config, None, page(None, false)).expect("query");
    });
    // Keyword search has its own section (`search`).

    let mut cursor = None;
    for _ in 0..50 {
        let response = vault_core::list_history(
            &paths,
            config,
            None,
            HistoryQuery { cursor: cursor.clone(), ..page(None, false) },
        )
        .expect("walk");
        cursor = response.next_cursor;
    }
    report("browse, page 51 by cursor, no total", 5, || {
        vault_core::list_history(
            &paths,
            config,
            None,
            HistoryQuery { cursor: cursor.clone(), ..page(None, false) },
        )
        .expect("deep page");
    });

    println!("\n## other History / Home reads");
    report("load_source_stats, first call (uncached)", 1, || {
        vault_core::load_source_stats(&paths, config, None).expect("stats");
    });
    report("load_source_stats, cached", 20, || {
        vault_core::load_source_stats(&paths, config, None).expect("stats");
    });
    let busiest_url: String = open_archive_connection(&paths, config, None)
        .expect("open")
        .query_row("SELECT url FROM urls WHERE id = 1", [], |row| row.get(0))
        .expect("url");
    report("get_url_detail, most-visited URL", 10, || {
        vault_core::get_url_detail(&paths, config, None, &busiest_url).expect("detail");
    });
    report("preview_data_wipe", 3, || {
        vault_core::preview_data_wipe(&paths, config, None).expect("preview");
    });
}

/// Fills the intelligence tables the doctor checks with one derived row per visit, a search-trail
/// member for every eighth visit, and 1,000 derived rows whose visit does not exist.
fn seeded_derived_rows(root: &Path, config: &AppConfig) {
    let ready = root.join("derived-rows-ready");
    if ready.exists() {
        return;
    }
    let paths = project_paths_with_root(root);
    let connection = open_intelligence_connection(&paths, config, None).expect("intelligence");
    let started = Instant::now();
    connection
        .execute_batch(
            "BEGIN;
             DELETE FROM visit_derived_facts;
             DELETE FROM search_trail_members;
             INSERT INTO visit_derived_facts
               (visit_id, profile_id, registrable_domain, canonical_url, computed_at)
             SELECT id, 'bench', '', '', '' FROM archive.visits;
             INSERT INTO visit_derived_facts
               (visit_id, profile_id, registrable_domain, canonical_url, computed_at)
             SELECT id + 1000000000, 'bench', '', '', '' FROM archive.visits LIMIT 1000;
             INSERT INTO search_trail_members (trail_id, profile_id, visit_id, ordinal, role)
             SELECT 'trail-' || (id / 32), 'bench', id, 0, 'query'
             FROM archive.visits WHERE id % 8 = 0;
             COMMIT;",
        )
        .expect("seed derived rows");
    println!("seeded derived rows in {:.1}s", started.elapsed().as_secs_f64());
    std::fs::write(&ready, b"").expect("ready marker");
}

fn bench_doctor(root: &Path, config: &AppConfig) {
    let paths = project_paths_with_root(root);
    unsafe { std::env::set_var("CHB_PROJECT_ROOT", root) };
    let intelligence = open_intelligence_connection(&paths, config, None).expect("intelligence");
    println!("\n## doctor stale-row checks");
    for (table, column) in
        [("visit_derived_facts", "visit_id"), ("search_trail_members", "visit_id")]
    {
        let old = format!(
            "SELECT COUNT(*) FROM {table}
             WHERE {column} NOT IN (SELECT id FROM archive.visits WHERE reverted_at IS NULL)"
        );
        let new = format!(
            "SELECT COUNT(*) FROM {table}
             WHERE NOT EXISTS (
               SELECT 1 FROM archive.visits AS visits
               WHERE visits.id = {table}.{column} AND visits.reverted_at IS NULL
             )"
        );
        for (shape, sql) in [("NOT IN (old)", &old), ("NOT EXISTS (new)", &new)] {
            println!("plan, {table}, {shape}:\n{}", query_plan(&intelligence, sql));
            report_memory(&format!("{table} stale count, {shape}"), 3, || {
                let stale: i64 =
                    intelligence.query_row(sql, [], |row| row.get(0)).expect("stale count");
                assert_eq!(stale, if table == "visit_derived_facts" { 1_000 } else { 0 });
            });
        }
    }
    report_memory("doctor (whole report)", 3, || {
        vault_core::doctor(&paths, config, None).expect("doctor");
    });
}

/// Search events for every eighth visit: 5,000 distinct queries, skewed so a few are common, one
/// in twenty navigational. Times are left NULL and migration 9 is unapplied, so the first read
/// below pays the real upgrade backfill.
fn seed_search_events(connection: &Connection) {
    let started = Instant::now();
    connection
        .execute_batch(
            "BEGIN;
             DELETE FROM search_events;
             INSERT INTO search_events
               (visit_id, profile_id, search_engine, raw_query, normalized_query, query_kind,
                computed_at)
             SELECT id, 'chrome:Default', 'google', 'Query ' || q, 'query ' || q,
                    CASE WHEN id % 160 = 0 THEN 'navigational' ELSE 'keyword' END, ''
             FROM (
               SELECT id, MIN((id * 2654435761) % 1000003 % 5000,
                              (id * 40503) % 999983 % 5000) AS q
               FROM archive.visits WHERE id % 8 = 0
             );
             DROP INDEX IF EXISTS idx_search_events_kind_time;
             UPDATE search_events SET visit_time_ms = NULL;
             DELETE FROM intelligence_schema_migrations WHERE version = 9;
             COMMIT;",
        )
        .expect("seed search events");
    println!("seeded search events in {:.1}s", started.elapsed().as_secs_f64());
}

fn bench_frequent_searches(root: &Path, config: &AppConfig) {
    use vault_core::{DateRange, FrequentSearchesRequest};
    let paths = project_paths_with_root(root);
    unsafe { std::env::set_var("CHB_PROJECT_ROOT", root) };
    let intelligence = open_intelligence_connection(&paths, config, None).expect("intelligence");
    seed_search_events(&intelligence);
    let events: i64 = intelligence
        .query_row("SELECT COUNT(*) FROM search_events", [], |row| row.get(0))
        .expect("count");
    println!("\n## frequent searches ({events} search events)");

    // The synthetic visits end in September 2025.
    let last_day = chrono::NaiveDate::from_ymd_opt(2025, 9, 12).expect("date");
    let request = |days: i64| FrequentSearchesRequest {
        date_range: DateRange {
            start: (last_day - chrono::Duration::days(days - 1)).format("%Y-%m-%d").to_string(),
            end: last_day.format("%Y-%m-%d").to_string(),
        },
        profile_id: None,
        limit: Some(10),
    };
    report("first read: migration 9 backfill + 30-day read", 1, || {
        vault_core::get_frequent_searches(&paths, config, None, &request(30)).expect("read");
    });
    for days in [7, 30, 90, 365] {
        report_memory(&format!("get_frequent_searches, {days} days"), 5, || {
            vault_core::get_frequent_searches(&paths, config, None, &request(days)).expect("read");
        });
    }
    // The same count without a stored time: join each event to its visit, as the other
    // range-scoped search reads (`get_search_queries`, `get_top_search_concepts`) do.
    let joined = "SELECT normalized_query, COUNT(*) AS searches
         FROM search_events
         JOIN archive.visits AS visits ON visits.id = search_events.visit_id
         WHERE search_events.query_kind = 'keyword'
           AND visits.visit_time_ms >= ?1 AND visits.visit_time_ms < ?2
         GROUP BY normalized_query
         ORDER BY searches DESC
         LIMIT 10";
    let plan = query_plan(&intelligence, &joined.replace("?1", "0").replace("?2", "1"));
    println!("plan, joined to archive.visits:\n{plan}");
    for days in [30, 365] {
        let end = START_MS + SPAN_MS;
        let start = end - days * 86_400_000;
        report(&format!("same count joined to archive.visits, {days} days"), 3, || {
            intelligence
                .prepare(joined)
                .expect("prepare")
                .query_map(params![start, end], |row| row.get::<_, String>(0))
                .expect("query")
                .for_each(drop);
        });
    }
}

fn bench_export(root: &Path, config: &AppConfig, key: Option<&str>) {
    use vault_core::{ExportFormat, ExportRequest};
    let paths = project_paths_with_root(root);
    unsafe { std::env::set_var("CHB_PROJECT_ROOT", root) };
    let kind = if key.is_some() { "encrypted" } else { "plaintext" };
    println!("\n## export_history, whole {kind} archive");
    // Export walks History in 1,000-row cursor pages; a page's cost decides the whole walk.
    let mut cursor = None;
    for page in 1..=20 {
        let started = Instant::now();
        let response = vault_core::list_history(
            &paths,
            config,
            key,
            HistoryQuery {
                limit: Some(1_000),
                include_total: Some(false),
                cursor: cursor.clone(),
                ..HistoryQuery::default()
            },
        )
        .expect("export page");
        if page % 5 == 0 {
            println!("  export page {page}: {:.1} ms", started.elapsed().as_secs_f64() * 1000.0);
        }
        cursor = response.next_cursor;
    }
    let formats = std::env::var("PATHKEEP_ARCHIVE_BENCH_EXPORT_FORMATS")
        .unwrap_or_else(|_| "jsonl,html".to_string());
    for name in formats.split(',').filter(|name| !name.trim().is_empty()) {
        let format = match name.trim() {
            "jsonl" => ExportFormat::Jsonl,
            "html" => ExportFormat::Html,
            "markdown" => ExportFormat::Markdown,
            "text" => ExportFormat::Text,
            other => panic!("unknown export format {other}"),
        };
        let mut written = (0, 0);
        report_memory(&format!("export_history, {name}"), 1, || {
            let result = vault_core::export_history(
                &paths,
                config,
                key,
                ExportRequest {
                    export_id: None,
                    query: HistoryQuery::default(),
                    format: format.clone(),
                },
            )
            .expect("export");
            let bytes = std::fs::metadata(&result.path).expect("export file").len();
            std::fs::remove_file(&result.path).expect("remove export");
            written = (result.count, bytes);
        });
        println!("  {} rows, {:.0} MiB file", written.0, written.1 as f64 / (1024.0 * 1024.0));
    }
}

fn query_plan(connection: &Connection, sql: &str) -> String {
    connection
        .prepare(&format!("EXPLAIN QUERY PLAN {sql}"))
        .expect("plan")
        .query_map([], |row| row.get::<_, String>(3))
        .expect("plan rows")
        .map(|row| format!("    {}", row.expect("plan row")))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Keyword search at three frequencies, with and without a date filter, the way the History screen
/// and the AI tools ask for it.
fn bench_search(paths: &ProjectPaths, config: &AppConfig, visits: u64) {
    let page = |q: Option<&str>, include_total: bool| HistoryQuery {
        q: q.map(str::to_string),
        limit: Some(100),
        include_total: Some(include_total),
        ..HistoryQuery::default()
    };
    // "topic 421" matches about 18,000 URLs (titles with "topic 421" and the prefix matches of
    // "421"); "topic 42" is in one title in 500 but with the prefix and trigram matches of "42"
    // about 90,000 URLs match; the rare term is one page in the middle of the id range with a
    // handful of visits; "topic" is in every title.
    let rare = format!("page {}", (visits / 4).max(1) / 3 + 1);
    let last_week = (START_MS + SPAN_MS - 7 * 86_400_000, START_MS + SPAN_MS);
    let first_year = (START_MS, START_MS + 365 * 86_400_000);
    for (label, q, runs, dates) in [
        ("keyword \"topic 421\"", "topic 421", 5, None),
        ("keyword \"topic 42\"", "topic 42", 5, None),
        ("rare keyword", rare.as_str(), 5, None),
        ("\"topic\"", "topic", 3, None),
        ("\"topic\", last 7 days", "topic", 3, Some(last_week)),
        ("\"topic\", first year", "topic", 3, Some(first_year)),
    ] {
        let search = |include_total: bool| HistoryQuery {
            start_time_ms: dates.map(|(start, _)| start),
            end_time_ms: dates.map(|(_, end)| end),
            ..page(Some(q), include_total)
        };
        let grouped = |include_total: bool| HistoryQuery {
            group_by_url: Some(true),
            ..search(include_total)
        };
        report(&format!("{label}, visits, first page, exact total"), runs, || {
            vault_core::list_history(paths, config, None, search(true)).expect("query");
        });
        report(&format!("{label}, visits, first page, no total"), runs, || {
            vault_core::list_history(paths, config, None, search(false)).expect("query");
        });
        report(&format!("{label}, visits newest-first, no total"), runs, || {
            vault_core::list_history(
                paths,
                config,
                None,
                HistoryQuery { sort: Some("newest".into()), ..search(false) },
            )
            .expect("query");
        });
        report(&format!("{label}, pages, first page, no total"), runs, || {
            vault_core::list_history(paths, config, None, grouped(false)).expect("query");
        });
        // The History header's count: the same search with `limit: 1` and the totals.
        report(&format!("{label}, pages, totals (limit 1)"), runs, || {
            vault_core::list_history(
                paths,
                config,
                None,
                HistoryQuery { limit: Some(1), ..grouped(true) },
            )
            .expect("query");
        });
        let first = vault_core::list_history(paths, config, None, grouped(false)).expect("query");
        let totals = vault_core::list_history(
            paths,
            config,
            None,
            HistoryQuery { limit: Some(1), ..grouped(true) },
        )
        .expect("query");
        println!(
            "|   {label}: {} pages, {:?} visits, exact: {}",
            totals.total, totals.total_visits, totals.total_exact
        );
        if first.next_cursor.is_some() {
            report(&format!("{label}, pages, second page by cursor"), runs, || {
                vault_core::list_history(
                    paths,
                    config,
                    None,
                    HistoryQuery { cursor: first.next_cursor.clone(), ..grouped(false) },
                )
                .expect("query");
            });
        }
    }
}

fn bench_encrypted(root: &Path, config: &AppConfig) {
    let paths = project_paths_with_root(root);
    unsafe { std::env::set_var("CHB_PROJECT_ROOT", root) };
    println!("\n## encrypted archive (100,000 visits; key derivation does not depend on size)");
    report("open_archive_connection, warm process", 10, || {
        drop(open_archive_connection(&paths, config, Some("bench-key")).expect("open"));
    });
    report("app_snapshot", 10, || {
        vault_worker::app_snapshot(Some("bench-key")).expect("snapshot");
    });
}

/// Builds (or reuses) an archive with `visits` visits under `root` and returns its config.
fn seeded_archive(root: &Path, visits: u64, key: Option<&str>) -> AppConfig {
    let paths = project_paths_with_root(root);
    let config = AppConfig {
        initialized: true,
        archive_mode: if key.is_some() { ArchiveMode::Encrypted } else { ArchiveMode::Plaintext },
        selected_profile_ids: PROFILES
            .iter()
            .map(|(browser, profile)| format!("{browser}:{profile}"))
            .collect(),
        ..AppConfig::default()
    };
    let ready = root.join("bench-ready");
    if ready.exists() {
        return config;
    }
    let _ = std::fs::remove_dir_all(root);
    save_config(&paths, &config).expect("save config");
    let started = Instant::now();
    insert_rows(&paths, &config, key, visits);
    println!("seeded {visits} visits in {:.1}s", started.elapsed().as_secs_f64());

    // A fresh open in this process projects the new rows into the search database, the same
    // first-launch path a real upgrade takes.
    let started = Instant::now();
    drop(open_archive_connection(&paths, &config, key).expect("projecting open"));
    println!("projected search documents in {:.1}s", started.elapsed().as_secs_f64());
    std::fs::write(&ready, b"").expect("ready marker");
    config
}

fn insert_rows(paths: &ProjectPaths, config: &AppConfig, key: Option<&str>, visits: u64) {
    let mut connection = open_archive_connection(paths, config, key).expect("open archive");
    let urls = (visits / 4).max(1);
    let transaction = connection.transaction().expect("transaction");
    transaction
        .execute(
            "INSERT INTO runs (id, run_type, trigger, started_at, finished_at, status, due_only)
             VALUES (1, 'backup', 'manual', '2026-01-01T00:00:00Z', '2026-01-01T00:10:00Z',
                     'success', 0)",
            [],
        )
        .expect("run");
    for (index, (browser, profile)) in PROFILES.iter().enumerate() {
        transaction
            .execute(
                "INSERT INTO source_profiles (id, browser_kind, profile_name, profile_path,
                   discovered_at, enabled, profile_key)
                 VALUES (?1, ?2, ?3, '/bench', '2026-01-01T00:00:00Z', 1, ?4)",
                params![index as i64 + 1, browser, profile, format!("{browser}:{profile}")],
            )
            .expect("profile");
    }
    {
        let mut insert_url = transaction
            .prepare(
                "INSERT INTO urls (id, url, title, visit_count, typed_count, first_visit_ms,
                   first_visit_iso, last_visit_ms, last_visit_iso, source_profile_id,
                   created_by_run_id, source_url_id, hidden, registrable_domain)
                 VALUES (?1, ?2, ?3, 0, 0, ?4, '', ?4, '', ?5, 1, ?1, 0, ?6)",
            )
            .expect("url statement");
        for id in 1..=urls {
            let domain = format!("site{}.example", id % DOMAINS);
            insert_url
                .execute(params![
                    id as i64,
                    format!("https://{domain}/page/{id}"),
                    format!("Page {id} about topic {}", id % 500),
                    START_MS,
                    profile_of(id),
                    domain,
                ])
                .expect("url");
        }
        let mut insert_visit = transaction
            .prepare(
                "INSERT INTO visits (url_id, source_visit_id, visit_time_ms, visit_time_iso,
                   transition_type, visit_duration_ms, source_profile_id, created_by_run_id)
                 VALUES (?1, ?2, ?3, '', 805306368, 0, ?4, 1)",
            )
            .expect("visit statement");
        let mut state: u64 = 0x2545_f491_4f6c_dd1d;
        for index in 0..visits {
            state = state.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
            // Skewed toward low ids so url 1 is the busiest page, like a real start page.
            let url_id = 1 + ((state >> 33) % urls).min((state >> 40) % urls);
            let time = START_MS + (index as i64) * (SPAN_MS / visits as i64);
            insert_visit
                .execute(params![url_id as i64, index.to_string(), time, profile_of(url_id)])
                .expect("visit");
        }
    }
    transaction
        .execute(
            "UPDATE runs SET stats_json = json_object(
               'totalProfiles', 3, 'totalUrls', ?1, 'totalVisits', ?2, 'totalDownloads', 0,
               'earliestVisitAt', '2020-09-13T12:26:40Z', 'latestVisitAt', '2025-09-12T12:26:40Z')
             WHERE id = 1",
            params![urls as i64, visits as i64],
        )
        .expect("cached totals");
    transaction.commit().expect("commit");
}

fn profile_of(url_id: u64) -> i64 {
    (url_id % PROFILES.len() as u64) as i64 + 1
}

/// Runs `call` `iterations` times and prints the median and slowest duration.
fn report(label: &str, iterations: usize, mut call: impl FnMut()) {
    let mut samples: Vec<Duration> = (0..iterations)
        .map(|_| {
            let started = Instant::now();
            call();
            started.elapsed()
        })
        .collect();
    samples.sort();
    let median = samples[samples.len() / 2];
    let slowest = samples[samples.len() - 1];
    println!(
        "| {label:<55} | median {:>9.2} ms | max {:>9.2} ms |",
        median.as_secs_f64() * 1000.0,
        slowest.as_secs_f64() * 1000.0
    );
}

/// Like [`report`], plus the peak memory above the starting point: Rust heap (counted by
/// [`CountingAllocator`]) and SQLite's own allocations (page cache, temporary indexes, sorters),
/// which do not go through the Rust allocator.
fn report_memory(label: &str, iterations: usize, mut call: impl FnMut()) -> (usize, i64) {
    let mut samples = Vec::with_capacity(iterations);
    let mut peak_heap = 0usize;
    let mut peak_sqlite = 0i64;
    for _ in 0..iterations {
        let heap_start = HEAP_CURRENT.load(Ordering::Relaxed);
        HEAP_PEAK.store(heap_start, Ordering::Relaxed);
        // SAFETY: plain reads/resets of SQLite's global memory counters.
        let sqlite_start = unsafe { rusqlite::ffi::sqlite3_memory_used() };
        unsafe { rusqlite::ffi::sqlite3_memory_highwater(1) };
        let started = Instant::now();
        call();
        samples.push(started.elapsed());
        peak_heap = peak_heap.max(HEAP_PEAK.load(Ordering::Relaxed).saturating_sub(heap_start));
        let sqlite_high = unsafe { rusqlite::ffi::sqlite3_memory_highwater(0) };
        peak_sqlite = peak_sqlite.max(sqlite_high - sqlite_start);
    }
    samples.sort();
    let mib = |bytes: f64| bytes / (1024.0 * 1024.0);
    println!(
        "| {label:<55} | median {:>9.2} ms | max {:>9.2} ms | heap +{:>8.1} MiB | sqlite +{:>8.1} MiB |",
        samples[samples.len() / 2].as_secs_f64() * 1000.0,
        samples[samples.len() - 1].as_secs_f64() * 1000.0,
        mib(peak_heap as f64),
        mib(peak_sqlite as f64),
    );
    (peak_heap, peak_sqlite)
}

static HEAP_CURRENT: AtomicUsize = AtomicUsize::new(0);
static HEAP_PEAK: AtomicUsize = AtomicUsize::new(0);

/// The system allocator plus a live-bytes counter and a resettable peak, so a call's peak heap
/// can be read without the process-lifetime high-water mark that `ru_maxrss` gives.
struct CountingAllocator;

impl CountingAllocator {
    fn grew(size: usize) {
        let now = HEAP_CURRENT.fetch_add(size, Ordering::Relaxed) + size;
        HEAP_PEAK.fetch_max(now, Ordering::Relaxed);
    }
}

// SAFETY: every call is forwarded to `System`; the counters never affect the returned memory.
unsafe impl GlobalAlloc for CountingAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let pointer = unsafe { System.alloc(layout) };
        if !pointer.is_null() {
            Self::grew(layout.size());
        }
        pointer
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        let pointer = unsafe { System.alloc_zeroed(layout) };
        if !pointer.is_null() {
            Self::grew(layout.size());
        }
        pointer
    }

    unsafe fn dealloc(&self, pointer: *mut u8, layout: Layout) {
        unsafe { System.dealloc(pointer, layout) };
        HEAP_CURRENT.fetch_sub(layout.size(), Ordering::Relaxed);
    }

    unsafe fn realloc(&self, pointer: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        let grown = unsafe { System.realloc(pointer, layout, new_size) };
        if !grown.is_null() {
            HEAP_CURRENT.fetch_sub(layout.size(), Ordering::Relaxed);
            Self::grew(new_size);
        }
        grown
    }
}

#[global_allocator]
static ALLOCATOR: CountingAllocator = CountingAllocator;

/// Failure mode (f): use the real export and allocator, comparing two archive sizes in an
/// otherwise idle integration-test process. This guards against collecting rows/strings again.
#[test]
fn export_heap_stays_bounded_as_archive_grows() {
    // Large opt-in benchmarks run alone so their allocator measurements remain comparable.
    if std::env::var("PATHKEEP_ARCHIVE_BENCH").as_deref() == Ok("1")
        || std::env::var("PATHKEEP_IMPORT_BATCH_BENCH").as_deref() == Ok("1")
    {
        return;
    }
    let root = tempfile::tempdir_in(std::env::current_dir().unwrap()).unwrap();
    let mut peaks = Vec::new();
    for visits in [10_000, 100_000] {
        let archive_root = root.path().join(format!("bounded-{visits}"));
        let config = seeded_archive(&archive_root, visits, None);
        let paths = project_paths_with_root(&archive_root);
        let (heap, _) = report_memory("bounded export heap", 1, || {
            let result = vault_core::export_history(
                &paths,
                &config,
                None,
                vault_core::ExportRequest {
                    export_id: None,
                    query: HistoryQuery::default(),
                    format: vault_core::ExportFormat::Jsonl,
                },
            )
            .unwrap();
            assert_eq!(result.count as u64, visits);
            std::fs::remove_file(result.path).unwrap();
        });
        assert!(heap < 2 * 1024 * 1024, "export allocated {heap} bytes above baseline");
        peaks.push(heap);
    }
    assert!(peaks[1] <= peaks[0] + 256 * 1024, "export heap grew with archive size: {peaks:?}");
}
