import fs from 'node:fs'
import path from 'node:path'

const workspaceRoot = process.cwd()
const docsRoot = path.join(workspaceRoot, 'docs')
const hubPath = path.join(docsRoot, 'vision-and-requirements.md')
const outputPath = path.join(workspaceRoot, 'llm.txt')

assertFileExists(hubPath)

const allDocPaths = collectDocFiles(docsRoot)
const orderedDocPaths = buildOrderedDocPaths(hubPath, allDocPaths)

fs.writeFileSync(outputPath, renderBundle(orderedDocPaths), 'utf8')

console.log(
  `Wrote ${relativeFromRoot(outputPath)} with ${orderedDocPaths.length} document(s).`,
)

function collectDocFiles(dirPath) {
  const entries = fs
    .readdirSync(dirPath, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name))

  const files = []

  for (const entry of entries) {
    const entryPath = path.join(dirPath, entry.name)

    if (entry.isDirectory()) {
      files.push(...collectDocFiles(entryPath))
      continue
    }

    if (isTextDoc(entry.name)) {
      files.push(entryPath)
    }
  }

  return files
}

function buildOrderedDocPaths(hubDocPath, allDocPaths) {
  const hubContent = fs.readFileSync(hubDocPath, 'utf8')
  const docIndexSection = extractDocIndexSection(hubContent)
  const allDocPathsSet = new Set(allDocPaths)
  const indexedPaths = [...docIndexSection.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)]
    .map((match) => match[1])
    .map((relativePath) =>
      resolveIndexedDocPath(hubDocPath, relativePath, allDocPathsSet),
    )

  const ordered = []
  const seen = new Set()

  for (const docPath of [hubDocPath, ...indexedPaths]) {
    if (seen.has(docPath)) {
      continue
    }

    seen.add(docPath)
    ordered.push(docPath)
  }

  const remainingPaths = allDocPaths.filter((docPath) => !seen.has(docPath))

  return [...ordered, ...remainingPaths]
}

function extractDocIndexSection(hubContent) {
  const match = hubContent.match(/^## 4\. 文檔目錄[\s\S]*$/m)

  if (!match) {
    throw new Error(
      'Could not find "## 4. 文檔目錄" in docs/vision-and-requirements.md.',
    )
  }

  return match[0]
}

function resolveIndexedDocPath(hubDocPath, relativePath, allDocPathsSet) {
  const docPath = path.resolve(path.dirname(hubDocPath), relativePath)

  if (!docPath.startsWith(docsRoot)) {
    throw new Error(`Indexed path is outside docs/: ${relativePath}`)
  }

  if (!allDocPathsSet.has(docPath)) {
    throw new Error(`Indexed document does not exist: ${relativePath}`)
  }

  return docPath
}

function renderBundle(docPaths) {
  const orderLines = docPaths
    .map((docPath, index) => `${index + 1}. ${relativeFromRoot(docPath)}`)
    .join('\n')

  const sections = docPaths
    .map((docPath) => renderDocSection(docPath))
    .join('\n\n')

  return [
    'PathKeep documentation bundle for LLM ingestion',
    '',
    'This file is generated by `bun run docs:llm`.',
    'Edit the source files under `docs/` and regenerate this file instead of editing it directly.',
    '',
    'Document order:',
    orderLines,
    '',
    sections,
    '',
  ].join('\n')
}

function renderDocSection(docPath) {
  const content = fs.readFileSync(docPath, 'utf8').trimEnd()
  const title = extractTitle(content)

  return [
    '='.repeat(80),
    `FILE: ${relativeFromRoot(docPath)}`,
    `TITLE: ${title}`,
    '='.repeat(80),
    '',
    content,
  ].join('\n')
}

function extractTitle(content) {
  const titleLine = content.split(/\r?\n/).find((line) => line.startsWith('# '))

  return titleLine ? titleLine.slice(2).trim() : 'Untitled'
}

function assertFileExists(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing required file: ${relativeFromRoot(filePath)}`)
  }
}

function isTextDoc(fileName) {
  return ['.md', '.mdx', '.txt'].includes(path.extname(fileName).toLowerCase())
}

function relativeFromRoot(filePath) {
  return path.relative(workspaceRoot, filePath).split(path.sep).join('/')
}
